### PR TITLE
[sailfish-webview] Always enable image download in context menu. JB#56516 OMP#JOLLA-559

### PR DESCRIPTION
**Pull request by mkenttala**

### CODE REVIEW

**Comment by mkenttala** [comment]
Now the question is which context menu items should be available for webview/email?

This pr enables the download option that in my opinion should be always available.

**Comment by atatarov** [comment]
> Now the question is which context menu items should be available for webview/email?
> 
> This pr enables the download option that in my opinion should be always available.

How it works when !downloadsEnabled? Is download actions triggered as it should?

**Comment by mkenttala** [comment]
> How it works when !downloadsEnabled? Is download actions triggered as it should?

Image download works according to my testing.

**Review by okodron — APPROVED** [review]

**Review by aroditelev — APPROVED** [review]

**Review by rainemak — APPROVED** [review]
Approving. Please rebase before merging if needed.

**Pull request merged**
