### PR TITLE
[sailfish-components-webview] Align file picking to the new parameters. JB#49804

### PR DESCRIPTION
**Pull request by rainemak**
Requires:
https://git.sailfishos.org/mer-core/embedlite-components/merge_requests/52

### CODE REVIEW

**Comment by shanechko** [comment]
LGTM

**Comment by llewelld** [comment]
I've not had a chance to test this yet either, but it also looks good.

**Comment by llewelld** [comment]
Testing filepicker with, for example, https://input-type-file.glitch.me/ works nicely. I'm having glitches with cut & paste, so will update to the latest gecko and recheck.

**Comment by llewelld** [comment]
> I'm having glitches with cut & paste, so will update to the latest gecko and recheck.
Yes, addressed by using a more recent version of esr52. So this looks to be working nicely. LGTM too.

**Pull request merged**
