### PR TITLE
[webview] Backport notification changes to 3.4.0. Contributes to JB#51257

### PR DESCRIPTION
**Pull request by adenexter**

### CODE REVIEW

**Comment by rainemak** [comment]
Will push the whole master to the upgrade-3.4.0 soonish.

**Comment by adenexter** [comment]
Okay... This change has a dependency to Silica which needs to go in first and the version dependencies in the spec file have to be lowered to match the upgrade-3.4.0 branch there.

**Comment by rainemak** [comment]
Note also that there was also some background change fix that needs to go the to Silica.

**Comment by pvuorela** [comment]
Suppose not needed if the whole branch is pushed, but for completeness: LGTM :)

**Pull request closed without merging**
