### PR TITLE
[sailfish-components-webview] Prevent binding loop in prompt dialog. Contributes to JB#55000

### PR DESCRIPTION
**Pull request by chriadam**

### CODE REVIEW

**Comment by chriadam** [comment]
Needs to be retargeted to master once https://github.com/sailfishos/sailfish-components-webview/pull/121 has been merged

**Comment by chriadam** [comment]
Note: also contains a prospective fix for JB#55035 which probably needs some discussion / review from @rainemak

**Review by okodron — COMMENTED** [review]
LGTM. @rainemak, @llewelld, @atatarov?

**Review by rainemak — APPROVED** [review]

**Comment by rainemak** [comment]
Please rebase before merging if you merge https://github.com/sailfishos/sailfish-components-webview/pull/121 or https://github.com/sailfishos/sailfish-components-webview/pull/123 first.

**Comment by chriadam** [comment]
Rebased.

**Pull request merged**
